### ISSUE TITLE
Possibility of running multiple queries in one properties file

### ISSUE THREAD

**Issue by framirezl** [ggrandes/jmysqlcli#1]
Possibility of running multiple queries in one properties file.
The output can be unique on standard output.

**Comment by ggrandes** [comment]
Use `sql.<N>=XXX` instead of `query=XXX`, detail in README.md

**Comment by ggrandes** [comment]
Feature released in [v1.0.1](/ggrandes/jmysqlcli/releases/v1.0.1)
